#!/usr/bin/env python3

'''
This script compares HIV drug resistance (HIVDR) profiles generated by Oxford 
Nanopore sequencing and Sanger sequencing. It quantifies agreement between the 
two methods at both the sample and drug level and generates statistical summaries 
and plots.

The analysis includes:
	Per-sample and per-drug concordance
	Overall percent agreement
	Cohen’s kappa statistic
	Heatmap visualization of concordance
	Bland–Altman plots of resistance levels
	McNemar’s test for paired categorical differences per drug

Integrase inhibitor drugs are excluded by default

Input Requirements
CSV files

The script expects two CSV files in the working directory:

	resistanceSummaries_nanopore.csv
	resistanceSummaries_sanger.csv
	
'''
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.contingency_tables import mcnemar
from sklearn.metrics import cohen_kappa_score
from matplotlib.colors import ListedColormap
from matplotlib.offsetbox import AnchoredText

# ---------------------------
# User-configurable plotting
# ---------------------------
FONT_SIZE_AXIS = 15      # axis labels
FONT_SIZE_TICKS = 12     # tick labels
FONT_SIZE_ANNOT = 12     # heatmap annotations
FONT_SIZE_COLORBAR = 15  # colorbar font

# ---------------------------
# 1. Load CSV files
# ---------------------------
nano_file = "resistanceSummaries_nanopore.csv"
sanger_file = "resistanceSummaries_sanger.csv"

nano = pd.read_csv(nano_file)
sanger = pd.read_csv(sanger_file)

# ---------------------------
# 2. Normalize sequence names
# ---------------------------
nano["SampleID"] = nano["Sequence Name"].str.extract(r"(Barcode\d+)")
sanger["SampleID"] = sanger["Sequence Name"].str.extract(r"(Barcode\d+)")

# Ensure samples match
if not set(nano["SampleID"]) == set(sanger["SampleID"]):
    missing_in_sanger = set(nano["SampleID"]) - set(sanger["SampleID"])
    missing_in_nano = set(sanger["SampleID"]) - set(nano["SampleID"])
    raise ValueError(f"Sample names do not match!\nMissing in Sanger: {missing_in_sanger}\nMissing in Nanopore: {missing_in_nano}")

nano.set_index("SampleID", inplace=True)
sanger.set_index("SampleID", inplace=True)

# ---------------------------
# 3. Detect drug Level columns, exclude integrase inhibitors
# ---------------------------
level_cols = [col for col in nano.columns if col.endswith("Level")]
if len(level_cols) == 0:
    raise ValueError("No '* Level' columns detected in your CSV files!")

# Remove integrase inhibitors
integrase_drugs = ["BIC", "CAB", "DTG", "EVG", "RAL"]
level_cols = [col for col in level_cols if not any(d in col for d in integrase_drugs)]

# Extract Level columns
nano_levels = nano[level_cols].copy()
sanger_levels = sanger[level_cols].copy()

# Clean drug names
drugs = [col.replace(" Level", "") for col in level_cols]
nano_levels.columns = drugs
sanger_levels.columns = drugs

# ---------------------------
# 4. Concordance table
# ---------------------------
concordance = (nano_levels == sanger_levels).astype(int)
concordance["Total Matches"] = concordance.sum(axis=1)

# Summary per drug
drug_concordance = pd.DataFrame({
    "Matches": (nano_levels == sanger_levels).sum(),
    "Total Samples": len(nano_levels),
})
drug_concordance["Percent Concordance"] = 100 * drug_concordance["Matches"] / drug_concordance["Total Samples"]

# Save tables
concordance.to_csv("HIVDR_comparison_table.csv")
drug_concordance.to_csv("HIVDR_concordance_summary.csv")
print("Saved comparison tables.")

# ---------------------------
# 5. Compute stats: percent agreement & Cohen's kappa
# ---------------------------
# Flatten all drug comparisons across all samples
nano_flat = nano_levels.values.flatten()
sanger_flat = sanger_levels.values.flatten()

percent_agreement = 100 * np.mean(nano_flat == sanger_flat)
kappa = cohen_kappa_score(nano_flat, sanger_flat)

# ---------------------------
# 6. Heatmap: samples on y-axis, drugs on x-axis
# ---------------------------
plt.figure(figsize=(14, 10))
ax = plt.gca()

# Ensure samples on rows, drugs on columns
heatmap_data = concordance[drugs].fillna(0).astype(int)

# Discrete Blues colormap: 0 = light, 1 = dark
cmap = ListedColormap([plt.get_cmap("Blues")(0.3), plt.get_cmap("Blues")(1.0)])

sns.heatmap(
    heatmap_data,
    annot=False,   # no numbers
    fmt=".0f",
    cmap=cmap,
    vmin=0,
    vmax=1,
    cbar_kws={"label": "Concordance", "ticks": [0, 1]},
    linewidths=0.5,
    linecolor='gray',
    ax=ax
)

# Axis labels
ax.set_xlabel("Drug", fontsize=18, fontweight="bold")
ax.set_ylabel("Sample", fontsize=18, fontweight="bold")

# Tick labels
ax.set_xticklabels(
    ax.get_xticklabels(),
    fontsize=14,
    fontweight="bold",
    rotation=45,
    ha="right"
)
ax.set_yticklabels(
    ax.get_yticklabels(),
    fontsize=12,
    fontweight="bold",
    rotation=0
)

# Title
ax.set_title(
    "Nanopore vs Sanger HIVDR Concordance per Sample",
    fontsize=20,
    fontweight="bold",
    pad=20
)

# Overlay percent agreement and Cohen's kappa
stats_text = f"Percent agreement: {percent_agreement:.1f}%\nCohen's kappa: {kappa:.2f}"
at = AnchoredText(
    stats_text,
    prop=dict(size=10, weight="bold"),
    frameon=True,
    loc="upper right",
    pad=0.5
)
at.patch.set_boxstyle("round,pad=0.5")
ax.add_artist(at)

plt.tight_layout()
plt.savefig("HIVDR_concordance_heatmap_with_stats.png", dpi=300)
plt.show()

# ---------------------------
# 7. Bland–Altman plots
# ---------------------------
plt.figure(figsize=(8, 6))
for drug in drugs:
    nano_vals = nano_levels[drug].fillna(0)
    sanger_vals = sanger_levels[drug].fillna(0)
    mean_vals = (nano_vals + sanger_vals) / 2
    diff_vals = nano_vals - sanger_vals
    plt.scatter(mean_vals, diff_vals, label=drug)

plt.axhline(0, color='grey', linestyle='--')
plt.xlabel("Mean Resistance Level", fontsize=FONT_SIZE_AXIS)
plt.ylabel("Difference (Nanopore - Sanger)", fontsize=FONT_SIZE_AXIS)
plt.title("Bland–Altman Plot for HIVDR Levels", fontsize=FONT_SIZE_AXIS)
plt.xticks(fontsize=FONT_SIZE_TICKS)
plt.yticks(fontsize=FONT_SIZE_TICKS)

plt.legend(
    fontsize=FONT_SIZE_ANNOT,
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    borderaxespad=0,
    frameon=False,
    markerscale=0.6  # shrink markers in legend
)

plt.tight_layout()
plt.savefig("HIVDR_bland_altman.png", dpi=300, bbox_inches='tight')
plt.close()
print("Saved Bland–Altman plot: HIVDR_bland_altman.png")

# ---------------------------
# 8. McNemar test for each drug
# ---------------------------
mcnemar_results = {}
for drug in drugs:
    table = pd.crosstab(nano_levels[drug], sanger_levels[drug])
    if table.shape == (2, 2):
        result = mcnemar(table)
        mcnemar_results[drug] = {"statistic": result.statistic, "pvalue": result.pvalue}
    else:
        mcnemar_results[drug] = {"statistic": np.nan, "pvalue": np.nan}

mcnemar_df = pd.DataFrame(mcnemar_results).T
mcnemar_df.to_csv("HIVDR_mcnemar_results.csv")
print("Saved McNemar test results: HIVDR_mcnemar_results.csv")
